line-length = 88
indent-width = 4

exclude = [
    ".git",
    "__pycache__",
    "__pypackages__",
    ".venv*",
    ".vscode",
    "*.db"
]

target-version = "py312"

[lint]

select = [
    "E",    # pycodestyle error
    "F",    # Pyflakes
    "W",    # pycodestyle warning
    "I",    # isort
    "DJ",   # flake8-django
    "B",    # flake8-bugbear
    "N"     # pep8-naming
]
ignore = ["E501"]
fixable = ["E4", "E7", "E9", "F", "I"]

[format]
line-ending = "lf"
