target-version = "py310"

line-length = 88
indent-width = 4

exclude = [
    ".git",
    "__pycache__",
    "__pypackages__",
    ".venv*",
    ".vscode",
    "*.db"
]

[lint]

select = [
    "E",    # pycodestyle error
    "F",    # Pyflakes
    "W",    # pycodestyle warning
    "DJ",   # flake8-django
    "B",    # flake8-bugbear
    "N"     # pep8-naming
]
ignore = ["E501", "E701"]
fixable = ["E4", "E7", "E9", "F"]

[format]
line-ending = "lf"
quote-style = "single"
